// frontend_old/src/pages/login.tsx
import React, { useState, useContext } from 'react'
import Layout from '../components/Layout'
import { Form, FormGroup, Label, Input, FormText } from 'reactstrap'
import Axios from 'axios'
import { ARCHITECT_CORE } from '../../config'
import { useRouter } from 'next/router'

export interface LoginProps {}

const Login: React.SFC<LoginProps> = () => {
	const [credentials, setCredentials] = useState({})
	const router = useRouter()

	async function handleSubmit(event) {
		event.preventDefault()
		try {
			const { status, data } = await Axios.post(`${ARCHITECT_CORE}/api/authentication/login`, credentials, { withCredentials: true })
			if (status == 200) {
				if (data.error === 403) {
					console.log('problem')
				} else {
					router.replace('/')
				}
			}
		} catch (error) {
			console.log(error)
		}
	}

	async function handleCredentials({ target }) {
		const { name, value } = target
		setCredentials({ ...credentials, [name]: value })
	}

	async function handleRememberMe({ srcElement }) {
		const { name, checked } = srcElement
		setCredentials({ ...credentials, [name]: checked })
	}

	return (
		<Layout>
			<div className='separator'></div>
			<div className='container form-loginout py-5'>
				<Form onSubmit={() => handleSubmit(event)}>
					<FormGroup>
						<Label for='email'>Email</Label>
						<Input type='email' name='email' id='email' placeholder='with a placeholder' onChange={() => handleCredentials(event)} />
					</FormGroup>
					<FormGroup>
						<Label for='password'>Password</Label>
						<Input type='password' name='password' id='password' placeholder='password placeholder' onChange={() => handleCredentials(event)} />
					</FormGroup>

					<FormGroup>
						<Label check>
							<Input type='checkbox' name='remember_me' id='remember_me' onChange={() => handleRememberMe(event)} />
							Se souvenir de moi
						</Label>
					</FormGroup>

					<button className='btn btn-primary'>Connexion</button>
				</Form>
			</div>
		</Layout>
	)
}

export default Login

// frontend/pages/authentication/login/index.vue
<template>
	<div>
		<div style="height: 25vh; background-color: rgb(0, 118, 214);"></div>
		<div class="login-page">
			<div class="container">
				<div class="login-info">
					<div class="content">
						<h1>Connexion</h1>
						<p class="lead">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Asperiores, perferendis. Iste doloremque sunt, odio perferendis dolor asperiores culpa quam ad.</p>
						<nuxt-link to="/authentication/register" class="btn btn-primary">Créer un compte</nuxt-link>
					</div>
				</div>
				<div class="login-form">
					<div class="container">
						<b-form @submit.prevent="handleSubmit">
							<b-form-group label="Adresse email :" label-for="email">
								<b-form-input id="email" v-model="form.email" type="email" required placeholder="Enter email"></b-form-input>
							</b-form-group>

							<b-form-group label="Mot de passe :" label-for="password">
								<b-form-input id="password" type="password" v-model="form.password" required placeholder="Enter name"></b-form-input>
							</b-form-group>

							<b-form-group id="input-group-4">
								<b-form-checkbox switch size="lg" v-model="form.checked">Se souvenir de moi</b-form-checkbox>
							</b-form-group>

							<b-button type="submit" variant="primary" @click.prevent="handleSubmit">Submit</b-button>
						</b-form>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	layout: 'master',
	data() {
		return {
			form: {
				email: '',
				password: '',
				remember_me: false
			}
		}
	},
	mounted() {
		console.log(this.$store.auth)
	},
	methods: {
		handleSubmit: async function () {
			try {
				const { data } = await this.$axios.post('/authentication/login', this.form)
				console.log(data)
				if (data.is_confirmed) {
					this.$store.commit('auth/login', { user: data.id, logged: true })
					this.$toast.success(`Bienvenue ${data.firstname}`)
					this.$router.replace('/')
				} else {
					this.$toast.info('Veuillez confirmer votre adresse email')
					this.$store.commit('auth/logout')
				}
			} catch (error) {
				console.log(error)
				this.$toast.error(``)
			}
		}
	},
	components: {}
}
</script>

<style scoped lang="scss" src="./style.scss"></style>
